
[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 11.25

# Основные цвета (background – фон, foreground – текст)
[colors.primary]
background = "#0d0d14"    # Тёмно-серый фон
foreground = "#ff5555"    # Белый текст

# Нормальные цвета терминала
[colors.normal]
black   = "#1a1a1a"       # Очень тёмный серый (почти черный)
red     = "#ff5555"       # Яркий красный – основное акцентное значение
green   = "#ffffff"       # Средний серый
yellow  = "#cccccc"       # Светлый серый
blue    = "#a6a6a6"       # Ещё более светлый серый
magenta = "#ff7777"       # Дополнительный оттенок красного (немного светлее)
cyan    = "#d9d9d9"       # Почти белый, но с лёгким серым оттенком
white   = "#ffffff"       # Чистый белый

# Яркие цвета терминала (оттенки для выделения)
[colors.bright]
black   = "#262626"       # Немного светлее основного черного оттенка
red     = "#ff6e6e"       # Ещё более яркий красный
green   = "#ffffff"       # Яркий серый
yellow  = "#d4d4d4"       # Ещё светлее серый, почти белый
blue    = "#b3b3b3"       # Светло-серый с мягким оттенком
magenta = "#ff8e8e"       # Самый яркий из оттенков красного для выделения
cyan    = "#e8e8e8"       # Очень светлый серый (почти белый)
white   = "#ffffff"       # Чистый белый

