-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local env = require("hyprland.env")
local execs = require("hyprland.execs")
local general = require("hyprland.general")
local rules = require("hyprland.rules")
local keybinds = require("hyprland.keybinds")

-- Можно также объединить всё в один require, если нужно:
-- require("hyprland.env")
-- require("hyprland.execs")
-- require("hyprland.general")
-- require("hyprland.rules")
-- require("hyprland.keybinds")

print("Hyprland configuration loaded successfully!")
