-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("GDK_SCALE", 2)

hl.env("XCURSOR_SIZE", 24)
