-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Autostart
hl.on("hyprland.start", function()
    hl.dsp.exec_cmd("hyprpaper")
    hl.dsp.exec_cmd("pypr")
    hl.dsp.exec_cmd("swaync")
    hl.dsp.exec_cmd("waybar")
    -- hl.dsp.exec_cmd("hyprlock") -- Закомментировано, так как обычно не нужно запускать при старте
    hl.dsp.exec_cmd("~/binds/hypr_session.sh")
end)
