-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "",
    mode     = "2560x1440@74.97",
    position = "auto",
    scale    = 1.6,
})

--1.6 - HiDPI

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
        --vfr = 1 #legacy
        vrr = 1,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        enable_swallow = true,
        -- отображение терминала при запуске в нём приложения
        swallow_regex = "(foot|kitty|allacritty|Alacritty)",
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        --new_window_takes_over_fullscreen = 2 # legacy
        allow_session_lock_restore = true,
        initial_workspace_tracking = false,
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 0,
        border_size = 3,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgb(4c566a)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = false,
    },
})

hl.config({
    decoration = {
        rounding = 0,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            --enabled = true
            --size = 4
            --passes = 1
            --vibrancy = 0.1696
            --xray = false
            --special = false
            --ignore_opacity = false
            enabled = true,
            xray = false,
            ignore_opacity = false,
            special = false,
            new_optimizations = true,
            size = 4,
            passes = 1,
            brightness = 1,
            noise = 0.01,
            contrast = 1,
            popups = true,
            popups_ignorealpha = 0.6,
        },
    },
})

hl.config({ animations = { enabled = true } })

hl.curve("bounce", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1.0 } } })
hl.curve("linear", { type = "bezier", points = { { 0.1, 1.0 }, { 0.0, 1.0 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.38, 0.04 }, { 1.0, 0.07 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "bounce", style = "popin" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "bounce", style = "popin" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 7, bezier = "linear", style="slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "bounce" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3, bezier = "linear", style="slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.6, bezier = "menu_accel" })

hl.config({
    opengl = {
        nvidia_anti_flicker = true,
        -- Recommended for most NVIDIA GPUs
    },
})

hl.config({
    render = {
        ctm_animation = 2,
        direct_scanout = 2,
    },
})
