# Прозрачность
#windowrule = opacity 0.9 0.8, ^(firefox)$
windowrule = match:class dolphin, opacity 0.9 0.8
windowrule = match:class vesktop, opacity 0.9 0.8
windowrule = match:class steam, opacity 0.9 0.8
#windowrule = match:class Alacritty, opacity 0.9 0.8

# mpv fullscreen monitor turn off fix
windowrule = content none, match:class .*mpv.*
windowrule = content none, match:title .*mpv.*

# Отключение краёв
windowrule = match:class firefox, border_size 0
windowrule = match:class librewolf, border_size 0
windowrule = match:class vesktop, border_size 0

# Блюр
layerrule = match:class wofi
#layerrule = blur, ^(alacritty)$

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    #pseudotile = true # legacy
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
