-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Прозрачность

--windowrule = opacity 0.9 0.8, ^(firefox)$

hl.window_rule({
    name  = "opacity_dolphin",
    match = {
        class = "dolphin",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name  = "opacity_vesktop",
    match = {
        class = "vesktop",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name  = "opacity_steam",
    match = {
        class = "steam",
    },
    opacity = "0.9 0.8",
})

--windowrule = match:class Alacritty, opacity 0.9 0.8

-- mpv fullscreen monitor turn off fix

hl.window_rule({
    name  = "mpv_content_none_class",
    match = {
        class = ".*mpv.*",
    },
    content = "none",
})

hl.window_rule({
    name  = "mpv_content_none_title",
    match = {
        title = ".*mpv.*",
    },
    content = "none",
})

-- Отключение краёв

hl.window_rule({
    name  = "bordersize_firefox",
    match = {
        class = "firefox",
    },
    border_size = 0,
})

hl.window_rule({
    name  = "bordersize_librewolf",
    match = {
        class = "librewolf",
    },
    border_size = 0,
})

hl.window_rule({
    name  = "bordersize_vesktop",
    match = {
        class = "vesktop",
    },
    border_size = 0,
})

hl.window_rule({
    name  = "bordersize_google_chrome",
    match = {
        class = "google-chrome",
    },
    border_size = 0,
})

-- Блюр

hl.layer_rule({
    name = "blur_wofi",
    match = {
        class = "wofi",
    },
    blur = true,
})

--layerrule = blur, ^(alacritty)$

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --pseudotile = true # legacy
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})
